#!/bin/bash

set -e

BRIDGES_REPO_PATH=../parity-bridges-common
OPEN_ETHEREUM_REPO_PATH=../parity

SKIP_WASM_BUILD=1
SKIP_MILLAU_NODE_BUILD=
SKIP_RIALTO_NODE_BUILD=
SKIP_ETHEREUM_RELAY_BUILD=1
SKIP_SUBSTRATE_RELAY_BUILD=
SKIP_RIALTO_PARACHAIN_COLLATOR_BUILD=

DISABLE_RIALTO=
DISABLE_MILLAU=
DISABLE_RIALTO_POA=1
DISABLE_WESTEND_TO_MILLAU=1
DISABLE_RIALTO_PARACHAIN=
GENERATE_LARGE_MESSAGES=
USE_COMPLEX_MILLAU_RIALTO_RELAY=1

# following two variables must be changed at once: either to ("", "debug") or to ("--release", "release")
BUILD_TYPE=--release
BUILD_FOLDER=release
