#!/bin/bash

set -e

BRIDGES_REPO_PATH=../parity-bridges-common
OPEN_ETHEREUM_REPO_PATH=../parity

SKIP_WASM_BUILD=1
DISABLE_RIALTO_POA=
DISABLE_WESTEND_TO_MILLAU=
GENERATE_LARGE_MESSAGES=
BUILD_TYPE=
BUILD_FOLDER=debug
