{
 "title": "{SOURCE_NAME} to {TARGET_NAME} messages: {LANE_ID} lane",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Best finalized {TARGET_NAME} headers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(label_replace({SOURCE_NAME}_to_{TARGET_NAME}_MessageLane_{LANE_ID}_best_block_numbers{type=~\"target|target_at_source\"}, \"type\", \"At {TARGET_NAME}\", \"type\", \"target\"), \"type\", \"At {SOURCE_NAME}\", \"type\", \"target_at_source\")",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Best finalized {SOURCE_NAME} headers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(label_replace({SOURCE_NAME}_to_{TARGET_NAME}_MessageLane_{LANE_ID}_best_block_numbers{type=~\"source|source_at_target\"}, \"type\", \"At {SOURCE_NAME}\", \"type\", \"source\"), \"type\", \"At {TARGET_NAME}\", \"type\", \"source_at_target\")",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Delivery race",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(label_replace({SOURCE_NAME}_to_{TARGET_NAME}_MessageLane_{LANE_ID}_lane_state_nonces{type=~\"source_latest_generated|target_latest_received\"}, \"type\", \"Latest message sent from {SOURCe_NAME}\", \"type\", \"source_latest_generated\"), \"type\", \"Latest message received by {TARGET_NAME}\", \"type\", \"target_latest_received\")",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Confirmations race",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(label_replace({SOURCE_NAME}_to_{TARGET_NAME}_MessageLane_{LANE_ID}_lane_state_nonces{type=~\"source_latest_confirmed|target_latest_received\"}, \"type\", \"Latest message confirmed by {TARGET_NAME} to {SOURCE_NAME}\", \"type\", \"source_latest_confirmed\"), \"type\", \"Latest message received by {SOURCE_NAME}\", \"type\", \"target_latest_received\")",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Delivery race lags",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scalar(max_over_time({SOURCE_NAME}_to_{TARGET_NAME}_MessageLane_{LANE_ID}_lane_state_nonces{type=\"source_latest_generated\"}[2m])) - scalar(max_over_time({SOURCE_NAME}_to_{TARGET_NAME}_MessageLane_{LANE_ID}_lane_state_nonces{type=\"target_latest_received\"}[2m]))",
     "legendFormat": "Undelivered messages at {TARGET_NAME}"
    }
   ]
  },
  {
   "title": "Confirmations race lags",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scalar(max_over_time({SOURCE_NAME}_to_{TARGET_NAME}_MessageLane_{LANE_ID}_lane_state_nonces{type=\"target_latest_received\"}[2m])) - scalar(max_over_time({SOURCE_NAME}_to_{TARGET_NAME}_MessageLane_{LANE_ID}_lane_state_nonces{type=\"source_latest_confirmed\"}[2m]))",
     "legendFormat": "Unconfirmed messages at {SOURCE_NAME}"
    }
   ]
  },
  {
   "title": "Reward lags",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scalar(max_over_time({SOURCE_NAME}_to_{TARGET_NAME}_MessageLane_{LANE_ID}_lane_state_nonces{type=\"source_latest_confirmed\"}[2m])) - scalar(max_over_time({SOURCE_NAME}_to_{TARGET_NAME}_MessageLane_{LANE_ID}_lane_state_nonces{type=\"target_latest_confirmed\"}[2m]))",
     "legendFormat": "Unconfirmed rewards at {TARGET_NAME}"
    }
   ]
  },
  {
   "title": "Relay process CPU usage (1 CPU = 100)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time({SOURCE_NAME}_to_{TARGET_NAME}_MessageLane_{LANE_ID}_process_cpu_usage_percentage[1m])"
    }
   ]
  },
  {
   "title": "System load average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{SOURCE_NAME}_to_{TARGET_NAME}_MessageLane_{LANE_ID}_system_average_load",
     "legendFormat": "Average system load in last {{over}}"
    }
   ]
  },
  {
   "title": "Memory used by relay process",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{SOURCE_NAME}_to_{TARGET_NAME}_MessageLane_{LANE_ID}_process_memory_usage_bytes / 1024 / 1024",
     "legendFormat": "Process memory, MB"
    }
   ]
  }
 ]
}